
//POST
export const FETCH_ALL ='FETCH_ALL_POSTS';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const LIKE_POST = 'LIKE_POST';

//COMMENT
export const FETCH_ALL_COMMENTS ='FETCH_COMMENTS';
export const CREATE_POST_COMMENT = 'CREATE_POST_COMMENT';
export const DELETE_POST_COMMENT = 'DELETE_POST_COMMENT';
export const LIKE_POST_COMMENT = 'LIKE_POST_COMMENT';

//AUTH
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';
export const SIGNIN = 'SIGNIN';

//NOTIFICATIONS
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const DELETE_NOTIFICATION ='DELETE_NOTIFICATION';