
//POST
export const FETCH_ALL ='FETCH_ALL_POSTS';
export const FETCH_USER_POSTS = 'FETCH_USER_POSTS';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const LIKE_POST = 'LIKE_POST';

//COMMENT
export const FETCH_ALL_COMMENTS ='FETCH_COMMENTS';
export const CREATE_POST_COMMENT = 'CREATE_POST_COMMENT';
export const DELETE_POST_COMMENT = 'DELETE_POST_COMMENT';
export const LIKE_POST_COMMENT = 'LIKE_POST_COMMENT';

//AUTH
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SIGNUP = 'SIGNUP';
export const SIGNIN = 'SIGNIN';
export const AUTH_REFRESH  ='AUTH_REFRESH';

//NOTIFICATIONS
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const DELETE_NOTIFICATION ='DELETE_NOTIFICATION';

//UPLOAD

export const UPLOAD_IMAGES = 'UPLOAD_IMAGES';


//PROFILE

export const FETCH_ALL_PROFILES = 'FETCH_ALL_PROFILES';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const ADD_FOLLOWER_TO_PROFILE = 'ADD_FOLLOWER_TO_PROFILE';
export const ADD_FOLLOWING_TO_PROFILE = 'ADD_FOLLOWING_TO_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';

//ERRORS

export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';